"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Vercel sets VERCEL=1 in its environment; locally it's unset.
ON_VERCEL = os.environ.get('VERCEL') == '1'


def load_env_file(path):
    """Read KEY=value lines from a local .env file into os.environ.
    Variables that are already set win, so a real environment always overrides the file."""
    try:
        lines = path.read_text(encoding='utf-8-sig').splitlines()
    except FileNotFoundError:
        return
    for line in lines:
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.removeprefix('export ').strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in '"\'':
            value = value[1:-1]
        os.environ.setdefault(key, value)


# Locally, secrets such as DATABASE_URL live in .env (gitignored).
# On Vercel they come from the project's Environment Variables instead.
if not ON_VERCEL:
    load_env_file(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if ON_VERCEL:
        raise ImproperlyConfigured('Set the DJANGO_SECRET_KEY environment variable in Vercel.')
    SECRET_KEY = 'django-insecure-local-dev-only-key-do-not-use-in-production'

# SECURITY WARNING: don't run with debug turned on in production!
# Off on Vercel unless DJANGO_DEBUG=1 is set; on locally.
DEBUG = os.environ.get('DJANGO_DEBUG', '0' if ON_VERCEL else '1') == '1'

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.vercel.app']
# Extra hosts, e.g. a custom domain: DJANGO_ALLOWED_HOSTS="todo.example.com,www.todo.example.com"
ALLOWED_HOSTS += [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()]

# Vercel terminates HTTPS in front of Django, so trust its forwarded-protocol header
# and accept form posts from the deployed origins.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_TRUSTED_ORIGINS = ['https://*.vercel.app'] + [
    f'https://{h}' for h in ALLOWED_HOSTS if h not in ('localhost', '127.0.0.1', '.vercel.app')
]

if ON_VERCEL:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'base'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'base.context_processors.task_counts',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

def find_database_url():
    """DATABASE_URL, or the copy that Vercel's Neon integration adds when it is connected
    with a custom prefix, e.g. downward_DATABASE_URL. Its *_DATABASE_URL_UNPOOLED twin
    doesn't match, so the pooled URL is the one used."""
    if os.environ.get('DATABASE_URL'):
        return os.environ['DATABASE_URL']
    prefixed = sorted(key for key, value in os.environ.items() if key.upper().endswith('_DATABASE_URL') and value)
    if len(prefixed) > 1:
        raise ImproperlyConfigured(
            f'Several database URLs are set ({", ".join(prefixed)}). Set DATABASE_URL to choose one.'
        )
    return os.environ[prefixed[0]] if prefixed else None


# With a database URL set (in .env locally, in Vercel's Environment Variables in production),
# Django uses that Postgres database, e.g. Neon. Without it, a local SQLite file.
# Vercel's filesystem is read-only, so a deployment always needs one.
database_url = find_database_url()  # lowercase, so it is not a Django setting shown on debug pages
if database_url:
    import dj_database_url
    DATABASES = {
        # conn_max_age=0: open a connection per request and close it after, which suits
        # serverless functions; Neon's pooler ("-pooler" host) keeps that cheap.
        'default': dj_database_url.parse(database_url, conn_max_age=0, ssl_require=True)
    }
    # A transaction-mode pooler (PgBouncer, which Neon's pooled URL uses) can't keep
    # server-side cursors open between transactions, so Django must not use them.
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True
    # Wait a little longer than libpq's default while a suspended Neon database wakes up.
    DATABASES['default'].setdefault('OPTIONS', {}).setdefault('connect_timeout', 15)
elif ON_VERCEL:
    raise ImproperlyConfigured(
        'No database URL on Vercel. Set DATABASE_URL (your Neon connection string) in the '
        "project's Environment Variables, or connect Neon under Storage, then redeploy."
    )
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS=[
    BASE_DIR/'static'
]
STATIC_ROOT=BASE_DIR/'staticfiles'
# Serve static files straight from STATICFILES_DIRS, so no collectstatic build step is needed.
WHITENOISE_USE_FINDERS=True

# Authentication
LOGIN_URL='login'
LOGIN_REDIRECT_URL='home'
LOGOUT_REDIRECT_URL='landing'
